/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'luigi.oliveira' at '03/01/17 11:17' with Gradle 3.2.1
 *
 * @author luigi.oliveira, @date 03/01/17 11:17
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
